#! /bin/bash
#1、写一个脚本，通过执行它可以将以下信息逐行输出到info.txt文件中
#  a.)bash版本
#  b.)X display的名字
#  c.)用户主目录信息

echo "bash版本：$BASH_VERSION" >> info.txt
echo "X display的名字：$DISPLAY" >> info.txt
echo "用户主目录信息：$HOME" >> info.txt
